services:
  - type: web
    name: visiora-api
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    autoDeployTrigger: 'off'
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: 10000
      - key: API_PREFIX
        value: /api/v1
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX
        value: 300
      - key: CORS_ORIGIN
        sync: false
      - key: AUTH_COOKIE_SAME_SITE
        value: none
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL
        value: 7d
      - key: S3_ENDPOINT
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: MAX_UPLOAD_MB
        value: 25
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
